apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata: 
  annotations: 
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "MEMORYMB"
    machine.openshift.io/vCPU: "VCPUCORES"
  generation: 1
  labels: 
    machine.openshift.io/cluster-api-cluster: CLUSTERNAME
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: MACHINESETNAME
  namespace: openshift-machine-api
spec: 
  replicas: NUMREPLICAS
  selector: 
    matchLabels: 
      machine.openshift.io/cluster-api-cluster: CLUSTERNAME
      machine.openshift.io/cluster-api-machineset: MACHINESETNAME
  template: 
    metadata: 
      labels: 
        machine.openshift.io/cluster-api-cluster: CLUSTERNAME
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: MACHINESETNAME
    spec: 
      metadata: {}
      providerSpec: 
        value: 
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret: 
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image: 
            offer: aro4
            publisher: azureopenshift
            resourceID: ""
            sku: AROSKU
            version: AROSKUVERSION
          kind: AzureMachineProviderSpec
          location: AZUREDC
          networkResourceGroup: NETWORKRG
          osDisk: 
            diskSizeGB: 128
            managedDisk: 
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: PUBLICLBNAME
          resourceGroup: PROTECTEDRG
          subnet: SUBNET
          userDataSecret: 
            name: worker-user-data
          vmSize: VMSKU
          vnet: VNETNAME
          zone: WHICHAZ
