apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: 'MEMORYMB'
    machine.openshift.io/vCPU: 'VCPUCORES'
  name: MACHINESETNAME
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTERNAME
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: NUMREPLICAS
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTERNAME
      machine.openshift.io/cluster-api-machineset: MACHINESETNAME
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTERNAME
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: MACHINESETNAME
    spec:
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: NETWORKRG
          publicLoadBalancer: PUBLICLBNAME
          userDataSecret:
            name: worker-user-data
          vnet: VNETNAME
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: 'WHICHAZ'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: PROTECTEDRG
          kind: AzureMachineProviderSpec
          location: AZUREDC
          vmSize: VMSKU
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: AROSKU
            version: AROSKUVERSION
          subnet: SUBNET
          apiVersion: azureproviderconfig.openshift.io/v1beta1
